import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ReduxProvider } from '../components/layouts/GlobalProvider';
import Navbar from '@/components/layouts/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Task Manager App',
  description: 'Generated by Shubham Mishra',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full grid grid-cols-3">
        <ReduxProvider>
          <div className='h-screen w-screen flex flex-col gap-6'>
            <section className='flex items-start'>
              <Navbar />
            </section>
            <main>{children}</main>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}